apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: cluster-resources
  namespace: argocd
spec:
  description: Contains basic cluster-resources
  destinations:
    - namespace: '*'
      server: https://kubernetes.default.svc
  sourceRepos:
    - '*'
  # allow to only see application resources from the specified namespace
  sourceNamespaces:
    - 'argocd'

  # Allow all namespaced-scoped resources to be created
  namespaceResourceWhitelist:
    - group: '*'
      kind: '*'
  # Allow all cluster-scoped resources to be created
  clusterResourceWhitelist:
    - group: '*'
      kind: '*'